database:
  host: postgres
  port: 5432
  name: postgres
  user: postgres
  password: postgres
testdb:
  name: postgres
  host: postgres
  port: 5432
  user: postgres
  password: postgres
token:
  duration: 1h
  key: qwertyuiopasdfghjklzxcvbnm123456
minio:
  endpoint: minio:9000
  access_key: minioadmin
  secret_key: minioadmin
  url_expiry: 168h
redis:
  host: redis
  port: 6379
  password: ""
timeout:
  duration: 10s
