version: "1"

packages:
  - path: "../database/db"
    name: "db"
    engine: "postgresql"
    schema: "../database/schema"
    queries: "../database/query"
    emit_interface: false
    emit_json_tags: true
    # emit_pointers_for_null_types: true
    # emit_pgx_pgtype: false
    sql_package: "pgx/v5"
    overrides:
      - db_type: "uuid"
        go_type: "github.com/google/uuid.UUID"
      - db_type: "timestamptz"
        go_type: "time.Time"
        

